# Generated by Django 2.0.5 on 2018-05-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_auto_20180522_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
