# Generated by Django 2.0.5 on 2018-05-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0006_topic_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
